In [3]:
import pandas as pd
import numpy as np

In [4]:
pd.set_option("display.max_columns",None) #display todas las columnas

In [5]:
df_talento = pd.read_csv("hr.csv")

In [6]:
df_talento.head(10)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41.0,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,2,Female,94,3,2,sALES eXECUTIVE,4.0,Single,5993.0,19479,8,Y,Yes,11,3,1,80.0,0,8,0.0,1,6,4,0,5.0
1,49.0,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,3,Male,61,2,2,rESEARCH sCIENTIST,2.0,Married,5130.0,24907,1,Y,No,23,4,4,NaN,1,10,3.0,3,10,7,1,7.0
2,37.0,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,4,Male,92,2,1,lABORATORY tECHNICIAN,3.0,Single,2090.0,2396,6,Y,Yes,15,3,2,NaN,0,7,3.0,3,0,0,0,0.0
3,33.0,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,4,Female,56,3,1,rESEARCH sCIENTIST,3.0,Married,2909.0,23159,1,Y,Yes,11,3,3,80.0,0,8,3.0,3,8,7,3,0.0
4,27.0,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,1,Male,40,3,1,lABORATORY tECHNICIAN,2.0,Married,3468.0,16632,9,Y,No,12,3,4,80.0,1,6,3.0,3,2,2,2,2.0
5,32.0,No,Travel_Frequently,1005,Research & Development,2,2,Life Sciences,1,8,4,Male,79,3,1,lABORATORY tECHNICIAN,4.0,Single,3068.0,11864,0,Y,No,13,3,3,80.0,0,8,2.0,2,7,7,3,6.0
6,59.0,No,Travel_Rarely,1324,Research & Development,3,3,Medical,1,10,3,Female,81,4,1,lABORATORY tECHNICIAN,1.0,Married,2670.0,9964,4,Y,NaN,20,4,1,NaN,3,12,3.0,2,1,0,0,NaN
7,30.0,No,Travel_Rarely,1358,NaN,24,1,Life Sciences,1,11,4,Male,67,3,1,lABORATORY tECHNICIAN,3.0,Divorced,2693.0,13335,1,Y,No,22,4,2,80.0,1,1,2.0,3,1,0,0,0.0
8,38.0,No,Travel_Frequently,216,Research & Development,23,3,Life Sciences,1,12,4,Male,44,2,3,mANUFACTURING dIRECTOR,3.0,Single,9526.0,8787,0,Y,No,21,4,2,80.0,0,10,2.0,3,9,7,1,8.0
9,36.0,No,Travel_Rarely,1299,Research & Development,27,3,NaN,1,13,3,Male,94,3,2,hEALTHCARE rEPRESENTATIVE,3.0,Married,5237.0,16577,6,Y,No,13,3,2,80.0,2,17,3.0,2,7,7,7,NaN

In [7]:
df_talento.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='str')

In [8]:
pd.Series(df_talento.columns)

0                          Age
1                    Attrition
2               BusinessTravel
3                    DailyRate
4                   Department
5             DistanceFromHome
6                    Education
7               EducationField
8                EmployeeCount
9               EmployeeNumber
10     EnvironmentSatisfaction
11                      Gender
12                  HourlyRate
13              JobInvolvement
14                    JobLevel
15                     JobRole
16             JobSatisfaction
17               MaritalStatus
18               MonthlyIncome
19                 MonthlyRate
20          NumCompaniesWorked
21                      Over18
22                    OverTime
23           PercentSalaryHike
24           PerformanceRating
25    RelationshipSatisfaction
26               StandardHours
27            StockOptionLevel
28           TotalWorkingYears
29       TrainingTimesLastYear
30             WorkLifeBalance
31              YearsAtCompany
32          YearsInCurrentRole
33     YearsSinceLastPromotion
34        YearsWithCurrManager
dtype: str

In [9]:
df_talento.shape #aqui vemos el número de filas, columnas

(1474, 35)

In [10]:
df_talento.info() #aqui vemos el tipo de datos, los nulos, columnas, etc

<class 'pandas.DataFrame'>
RangeIndex: 1474 entries, 0 to 1473
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1401 non-null   float64
 1   Attrition                 1474 non-null   str
 2   BusinessTravel            1357 non-null   str
 3   DailyRate                 1474 non-null   int64
 4   Department                1445 non-null   str
 5   DistanceFromHome          1474 non-null   int64
 6   Education                 1474 non-null   int64
 7   EducationField            1416 non-null   str
 8   EmployeeCount             1474 non-null   int64
 9   EmployeeNumber            1474 non-null   int64
 10  EnvironmentSatisfaction   1474 non-null   int64
 11  Gender                    1474 non-null   str
 12  HourlyRate                1474 non-null   int64
 13  JobInvolvement            1474 non-null   int64
 14  JobLevel                  1474 non-null   int64
 15  JobRole                   1474 non-null   str
 16  JobSatisfaction           1445 non-null   float64
 17  MaritalStatus             1342 non-null   str
 18  MonthlyIncome             1460 non-null   float64
 19  MonthlyRate               1474 non-null   int64
 20  NumCompaniesWorked        1474 non-null   int64
 21  Over18                    1474 non-null   str
 22  OverTime                  1430 non-null   str
 23  PercentSalaryHike         1474 non-null   int64
 24  PerformanceRating         1474 non-null   int64
 25  RelationshipSatisfaction  1474 non-null   int64
 26  StandardHours             1310 non-null   float64
 27  StockOptionLevel          1474 non-null   int64
 28  TotalWorkingYears         1474 non-null   int64
 29  TrainingTimesLastYear     1386 non-null   float64
 30  WorkLifeBalance           1474 non-null   int64
 31  YearsAtCompany            1474 non-null   int64
 32  YearsInCurrentRole        1474 non-null   int64
 33  YearsSinceLastPromotion   1474 non-null   int64
 34  YearsWithCurrManager      1326 non-null   float64
dtypes: float64(6), int64(20), str(9)
memory usage: 403.2 KB

In [11]:
df_talento.duplicated().sum() #supuestamente hay 4 duplicados.

np.int64(4)

## columnas a modificar tras primera visualización

Age: float a int?

César:

- Attrition - Baja personal o rotación general
- DailyRate - Tarifa diaria, en código, dinero ??
- HourlyRate - Tarifa horaria, código o dinero ?? 
- JobLevel - Nivel de puesto ( jefe - intermedio - "peón")
-

In [12]:
df_talento[["MonthlyIncome", "MonthlyRate"]].sample(10)

      MonthlyIncome  MonthlyRate
322          5055.0        10557
710         17444.0        20489
564          6632.0        12388
1381         2144.0         2122
1096        16437.0        17381
1238         3295.0        12862
1158         5768.0        26493
647         10903.0         9129
32           2206.0        16117
337          3983.0         7621

In [13]:
df_talento["ProfitMargen"] = (1 - df_talento["MonthlyIncome"] / df_talento["MonthlyRate"]) * 100

In [14]:
display(round(df_talento[["ProfitMargen", "MonthlyRate", "MonthlyIncome", "JobRole"]]), 2)

      ProfitMargen  MonthlyRate  MonthlyIncome                   JobRole
0             69.0        19479         5993.0          sALES eXECUTIVE
1             79.0        24907         5130.0       rESEARCH sCIENTIST
2             13.0         2396         2090.0    lABORATORY tECHNICIAN
3             87.0        23159         2909.0       rESEARCH sCIENTIST
4             79.0        16632         3468.0    lABORATORY tECHNICIAN
...            ...          ...            ...                       ...
1469          57.0        10228         4404.0    lABORATORY tECHNICIAN
1470          64.0        23490         8463.0          sALES eXECUTIVE
1471          83.0        26250         4450.0   mANUFACTURING dIRECTOR
1472          87.0        11585         1555.0          hUMAN rESOURCES
1473          48.0        18787         9724.0       rESEARCH sCIENTIST

[1474 rows x 4 columns]

2

In [15]:
df_talento["DailyRate"].sample(10)

182     1356
1311    1431
269     1403
531     1018
822     1003
914      177
596     1258
436      587
1103     492
989     1439
Name: DailyRate, dtype: int64

In [16]:
round(df_talento.isna().sum()/df_talento.shape[0] * 100), 2

(Age                          5.0
 Attrition                    0.0
 BusinessTravel               8.0
 DailyRate                    0.0
 Department                   2.0
 DistanceFromHome             0.0
 Education                    0.0
 EducationField               4.0
 EmployeeCount                0.0
 EmployeeNumber               0.0
 EnvironmentSatisfaction      0.0
 Gender                       0.0
 HourlyRate                   0.0
 JobInvolvement               0.0
 JobLevel                     0.0
 JobRole                      0.0
 JobSatisfaction              2.0
 MaritalStatus                9.0
 MonthlyIncome                1.0
 MonthlyRate                  0.0
 NumCompaniesWorked           0.0
 Over18                       0.0
 OverTime                     3.0
 PercentSalaryHike            0.0
 PerformanceRating            0.0
 RelationshipSatisfaction     0.0
 StandardHours               11.0
 StockOptionLevel             0.0
 TotalWorkingYears            0.0
 TrainingTimesLastYear        6.0
 WorkLifeBalance              0.0
 YearsAtCompany               0.0
 YearsInCurrentRole           0.0
 YearsSinceLastPromotion      0.0
 YearsWithCurrManager        10.0
 ProfitMargen                 1.0
 dtype: float64,
 2)

In [17]:
df_talento["Over18"].unique()

<StringArray>
['Y']
Length: 1, dtype: str

In [18]:
df_talento.sample()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,ProfitMargen
690,31.0,No,NaN,616,Research & Development,12,3,Medical,1,961,4,Female,41,3,2,hEALTHCARE rEPRESENTATIVE,4.0,Married,5855.0,17369,0,Y,Yes,11,3,3,80.0,2,10,2.0,1,9,7,8,5.0,66.290518

In [19]:
df_talento["EmployeeCount"].unique()

array([1])

In [20]:
df_talento["JobSatisfaction"].isna().sum()

np.int64(29)

In [21]:
df_talento["Age"].isna().sum()

np.int64(73)

In [22]:
df_talento["Age"].dtype

dtype('float64')

In [23]:
display(df_talento.describe(include="str").T)

               count unique                     top  freq
Attrition       1474      2                      No  1236
BusinessTravel  1357      3           Travel_Rarely   955
Department      1445      3  Research & Development   941
EducationField  1416      6           Life Sciences   582
Gender          1474      2                    Male   885
JobRole         1474      9        sALES eXECUTIVE    327
MaritalStatus   1342      4                 Married   604
Over18          1474      1                       Y  1474
OverTime        1430      2                      No  1025

In [24]:
display(round(df_talento.describe(exclude=str).T), 2)

,count,mean,std,min,25%,50%,75%,max
Age,1401.0,37.0,9.0,18.0,30.0,36.0,43.0,60.0
DailyRate,1474.0,803.0,404.0,102.0,465.0,803.0,1157.0,1499.0
DistanceFromHome,1474.0,9.0,8.0,1.0,2.0,7.0,14.0,29.0
Education,1474.0,3.0,1.0,1.0,2.0,3.0,4.0,5.0
EmployeeCount,1474.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0
EmployeeNumber,1474.0,1024.0,602.0,1.0,489.0,1020.0,1556.0,2068.0
EnvironmentSatisfaction,1474.0,3.0,1.0,1.0,2.0,3.0,4.0,4.0
HourlyRate,1474.0,66.0,20.0,30.0,48.0,66.0,84.0,100.0
JobInvolvement,1474.0,3.0,1.0,1.0,2.0,3.0,3.0,4.0
JobLevel,1474.0,2.0,1.0,1.0,1.0,2.0,3.0,5.0
JobSatisfaction,1445.0,3.0,1.0,1.0,2.0,3.0,4.0,4.0
MonthlyIncome,1460.0,6497.0,4706.0,1009.0,2909.0,4907.0,8377.0,19999.0
MonthlyRate,1474.0,14329.0,7120.0,2094.0,8054.0,14248.0,20466.0,26999.0
NumCompaniesWorked,1474.0,3.0,2.0,0.0,1.0,2.0,4.0,9.0
PercentSalaryHike,1474.0,15.0,4.0,11.0,12.0,14.0,18.0,25.0
PerformanceRating,1474.0,3.0,0.0,3.0,3.0,3.0,3.0,4.0
RelationshipSatisfaction,1474.0,3.0,1.0,1.0,2.0,3.0,4.0,4.0
StandardHours,1310.0,80.0,0.0,80.0,80.0,80.0,80.0,80.0
StockOptionLevel,1474.0,1.0,1.0,0.0,0.0,1.0,1.0,3.0
TotalWorkingYears,1474.0,11.0,8.0,0.0,6.0,10.0,15.0,40.0
TrainingTimesLastYear,1386.0,3.0,1.0,0.0,2.0,3.0,3.0,6.0
WorkLifeBalance,1474.0,3.0,1.0,1.0,2.0,3.0,3.0,4.0
YearsAtCompany,1474.0,7.0,6.0,0.0,3.0,5.0,9.0,40.0
YearsInCurrentRole,1474.0,4.0,4.0,0.0,2.0,3.0,7.0,18.0
YearsSinceLastPromotion,1474.0,2.0,3.0,0.0,0.0,1.0,3.0,15.0
YearsWithCurrManager,1326.0,4.0,4.0,0.0,2.0,3.0,7.0,17.0
ProfitMargen,1460.0,33.0,84.0,-818.0,23.0,60.0,78.0,96.0

2

In [25]:
df_talento["JobRole"] = df_talento["JobRole"].str.lower()

In [26]:
df_talento["JobRole"]

0               sales executive
1            research scientist
2         laboratory technician
3            research scientist
4         laboratory technician
                  ...
1469      laboratory technician
1470            sales executive
1471     manufacturing director
1472            human resources
1473         research scientist
Name: JobRole, Length: 1474, dtype: str

In [27]:
df_talento.duplicated().sum()

np.int64(4)

In [28]:
df_talento["JobRole"].str.strip().str.capitalize()

0              Sales executive
1           Research scientist
2        Laboratory technician
3           Research scientist
4        Laboratory technician
                 ...
1469     Laboratory technician
1470           Sales executive
1471    Manufacturing director
1472           Human resources
1473        Research scientist
Name: JobRole, Length: 1474, dtype: str

Funcion para sacar datos de los dataframes y las columnas

In [38]:
def info_df(dataframe, search=None, sample_n=5):
    print("Informacion sobre el dataframe:")
    dataframe.info()
    print("-" * 100)

    print("La descripcion del dataframe de strings:")
    display(dataframe.describe(include=[object, "category"]).T)
    print("-" * 100)

    print("La descripcion del dataframe numerico:")
    display(dataframe.describe(exclude=[object, "category"]).T)
    print("-" * 100)

    print(f"La forma del dataframe es:\n{dataframe.shape[0]} filas\n{dataframe.shape[1]} columnas")
    print("-" * 100)

    if search:
        search_str = str(search).strip().lower()
        cols_match = [c for c in dataframe.columns if search_str in c.lower()]
        print(f"Columnas que contienen '{search}': {cols_match if cols_match else 'ninguna'}")

        mask = dataframe.apply(lambda col: col.astype(str).str.contains(search_str, case=False, na=False))
        rows_match = dataframe[mask.any(axis=1)]
        print(f"Filas con '{search}': {rows_match.shape[0]} encontrada(s)")
        if not rows_match.empty:
            display(rows_match.head(sample_n))
        else:
            print("No se encontraron filas con ese criterio.")
        print("-" * 100)

    print("Muestra del dataframe:")
    display(dataframe.sample(min(sample_n, len(dataframe))))

In [39]:
info_df(df_talento)

Informacion sobre el dataframe:
<class 'pandas.DataFrame'>
RangeIndex: 1474 entries, 0 to 1473
Data columns (total 36 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1401 non-null   float64
 1   Attrition                 1474 non-null   str
 2   BusinessTravel            1357 non-null   str
 3   DailyRate                 1474 non-null   int64
 4   Department                1445 non-null   str
 5   DistanceFromHome          1474 non-null   int64
 6   Education                 1474 non-null   int64
 7   EducationField            1416 non-null   str
 8   EmployeeCount             1474 non-null   int64
 9   EmployeeNumber            1474 non-null   int64
 10  EnvironmentSatisfaction   1474 non-null   int64
 11  Gender                    1474 non-null   str
 12  HourlyRate                1474 non-null   int64
 13  JobInvolvement            1474 non-null   int64
 14  JobLevel                  1474 non-null   int64
 15  JobRole                   1474 non-null   str
 16  JobSatisfaction           1445 non-null   float64
 17  MaritalStatus             1342 non-null   str
 18  MonthlyIncome             1460 non-null   float64
 19  MonthlyRate               1474 non-null   int64
 20  NumCompaniesWorked        1474 non-null   int64
 21  Over18                    1474 non-null   str
 22  OverTime                  1430 non-null   str
 23  PercentSalaryHike         1474 non-null   int64
 24  PerformanceRating         1474 non-null   int64
 25  RelationshipSatisfaction  1474 non-null   int64
 26  StandardHours             1310 non-null   float64
 27  StockOptionLevel          1474 non-null   int64
 28  TotalWorkingYears         1474 non-null   int64
 29  TrainingTimesLastYear     1386 non-null   float64
 30  WorkLifeBalance           1474 non-null   int64
 31  YearsAtCompany            1474 non-null   int64
 32  YearsInCurrentRole        1474 non-null   int64
 33  YearsSinceLastPromotion   1474 non-null   int64
 34  YearsWithCurrManager      1326 non-null   float64
 35  ProfitMargen              1460 non-null   float64
dtypes: float64(7), int64(20), str(9)
memory usage: 414.7 KB
----------------------------------------------------------------------------------------------------
La descripcion del dataframe de strings:

C:\Users\fabih\AppData\Local\Temp\ipykernel_28904\376643467.py:7: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  display(dataframe.describe(include=[object, "category"]).T)

               count unique                     top  freq
Attrition       1474      2                      No  1236
BusinessTravel  1357      3           Travel_Rarely   955
Department      1445      3  Research & Development   941
EducationField  1416      6           Life Sciences   582
Gender          1474      2                    Male   885
JobRole         1474      9        sales executive    327
MaritalStatus   1342      4                 Married   604
Over18          1474      1                       Y  1474
OverTime        1430      2                      No  1025

----------------------------------------------------------------------------------------------------
La descripcion del dataframe numerico:

,count,mean,std,min,25%,50%,75%,max
Age,1401.0,36.944325,9.105009,18.000000,30.000000,36.000000,43.000000,60.000000
DailyRate,1474.0,802.702171,403.539530,102.000000,465.000000,803.000000,1157.000000,1499.000000
DistanceFromHome,1474.0,9.199457,8.104266,1.000000,2.000000,7.000000,14.000000,29.000000
Education,1474.0,2.911126,1.024267,1.000000,2.000000,3.000000,4.000000,5.000000
EmployeeCount,1474.0,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000
EmployeeNumber,1474.0,1024.471506,602.421193,1.000000,488.750000,1020.500000,1555.750000,2068.000000
EnvironmentSatisfaction,1474.0,2.723881,1.093280,1.000000,2.000000,3.000000,4.000000,4.000000
HourlyRate,1474.0,65.887381,20.310444,30.000000,48.000000,66.000000,83.750000,100.000000
JobInvolvement,1474.0,2.729986,0.712861,1.000000,2.000000,3.000000,3.000000,4.000000
JobLevel,1474.0,2.063772,1.106055,1.000000,1.000000,2.000000,3.000000,5.000000
JobSatisfaction,1445.0,2.728720,1.106409,1.000000,2.000000,3.000000,4.000000,4.000000
MonthlyIncome,1460.0,6497.448630,4706.059294,1009.000000,2909.000000,4907.000000,8377.000000,19999.000000
MonthlyRate,1474.0,14328.611940,7120.225285,2094.000000,8054.500000,14248.500000,20465.750000,26999.000000
NumCompaniesWorked,1474.0,2.688602,2.496443,0.000000,1.000000,2.000000,4.000000,9.000000
PercentSalaryHike,1474.0,15.206920,3.659274,11.000000,12.000000,14.000000,18.000000,25.000000
PerformanceRating,1474.0,3.153324,0.360422,3.000000,3.000000,3.000000,3.000000,4.000000
RelationshipSatisfaction,1474.0,2.713704,1.080338,1.000000,2.000000,3.000000,4.000000,4.000000
StandardHours,1310.0,80.000000,0.000000,80.000000,80.000000,80.000000,80.000000,80.000000
StockOptionLevel,1474.0,0.794437,0.851784,0.000000,0.000000,1.000000,1.000000,3.000000
TotalWorkingYears,1474.0,11.274084,7.785972,0.000000,6.000000,10.000000,15.000000,40.000000
TrainingTimesLastYear,1386.0,2.797980,1.296882,0.000000,2.000000,3.000000,3.000000,6.000000
WorkLifeBalance,1474.0,2.761872,0.705625,1.000000,2.000000,3.000000,3.000000,4.000000
YearsAtCompany,1474.0,6.996608,6.122920,0.000000,3.000000,5.000000,9.000000,40.000000
YearsInCurrentRole,1474.0,4.221845,3.622032,0.000000,2.000000,3.000000,7.000000,18.000000
YearsSinceLastPromotion,1474.0,2.183175,3.219356,0.000000,0.000000,1.000000,3.000000,15.000000
YearsWithCurrManager,1326.0,4.061840,3.517603,0.000000,2.000000,3.000000,7.000000,17.000000
ProfitMargen,1460.0,33.492488,83.580463,-817.741176,22.662029,60.319155,77.826913,96.262825

----------------------------------------------------------------------------------------------------
La forma del dataframe es:
1474 filas
36 columnas
----------------------------------------------------------------------------------------------------
Muestra del dataframe:

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,ProfitMargen
580,35.0,No,Travel_Rarely,384,Sales,8,4,Life Sciences,1,805,1,Female,72,3,1,sales representative,4.0,Married,2572.0,20317,1,Y,No,16,3,2,80.0,1,3,1.0,2,3,2,0,2.0,87.340651
497,44.0,No,Travel_Rarely,1315,Research & Development,3,4,Other,1,671,4,Male,35,3,5,manager,4.0,Married,19513.0,9358,4,Y,Yes,12,3,1,80.0,1,26,2.0,4,2,2,0,1.0,-108.516777
471,38.0,No,Travel_Rarely,1495,Research & Development,10,3,Medical,1,634,3,Female,76,3,2,healthcare representative,3.0,Married,9824.0,22174,3,Y,No,19,3,3,80.0,1,18,4.0,3,1,0,0,0.0,55.695860
249,45.0,No,Travel_Frequently,1199,Research & Development,7,4,Life Sciences,1,341,1,Male,77,4,2,manufacturing director,3.0,NaN,6434.0,5118,4,Y,No,17,3,4,80.0,1,9,1.0,3,3,2,0,2.0,-25.713169
547,42.0,Yes,Travel_Frequently,933,NaN,19,3,Medical,1,752,3,Male,57,4,1,research scientist,3.0,Divorced,2759.0,20366,6,Y,Yes,12,3,4,80.0,0,7,2.0,3,2,2,2,2.0,86.452912

In [49]:
def analisis_columnas (dataframe):
    for columna in dataframe:
        print(f"Columna: {columna}\n {"-" * 100}")
        print(f"Valores unicos: {dataframe[columna].unique()}\n {"-" * 100}")
        print(f"Valores duplicados: {dataframe[columna].duplicated().sum()}\n {"-" * 100}")
        print(f"Valores nulos: {dataframe[columna].isna().sum()}\n {"-" * 100}")
        print(f"El tipo de dato: {dataframe[columna].dtype}\n {"-" * 100}")

In [50]:
analisis_columnas(df_talento)

Columna: Age
 ----------------------------------------------------------------------------------------------------
Valores unicos: [41. 49. 37. 33. 27. 32. 59. 30. 38. 36. 35. 29. 31. 34. 28. 22. 53. 24.
 21. 42. 44. 46. 39. 43. 50. 26. 48. nan 55. 45. 56. 23. 51. 40. 54. 58.
 20. 25. 19. 57. 52. 47. 18. 60.]
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 1430
 ----------------------------------------------------------------------------------------------------
Valores nulos: 73
 ----------------------------------------------------------------------------------------------------
El tipo de dato: float64
 ----------------------------------------------------------------------------------------------------
Columna: Attrition
 ----------------------------------------------------------------------------------------------------
Valores unicos: <StringArray>
['Yes', 'No']
Length: 2, dtype: str
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 1472
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: str
 ----------------------------------------------------------------------------------------------------
Columna: BusinessTravel
 ----------------------------------------------------------------------------------------------------
Valores unicos: <StringArray>
['Travel_Rarely', 'Travel_Frequently', 'Non-Travel', nan]
Length: 4, dtype: str
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 1470
 ----------------------------------------------------------------------------------------------------
Valores nulos: 117
 ----------------------------------------------------------------------------------------------------
El tipo de dato: str
 ----------------------------------------------------------------------------------------------------
Columna: DailyRate
 ----------------------------------------------------------------------------------------------------
Valores unicos: [1102  279 1373 1392  591 1005 1324 1358  216 1299  809  153  670 1346
  103 1389  334 1123 1219  371  673 1218  419  391  699 1282 1125  691
  477  705  924 1459  125  895  813 1273  869  890  852 1141  464 1240
 1357  994  721 1360 1065  408 1211 1229  626 1434 1488 1097 1443  515
  853 1142  655 1115  427  653  989 1435 1223  836 1195 1339  664  318
 1225 1328 1082  548  132  746  776  193  397  945 1214  111  573 1153
 1400  541  432  288  669  530  632 1334  638 1093 1217 1353  120  682
  489  807  827  871  665 1040 1420  240 1280  534 1456  658  142 1127
 1031 1189 1354 1467  922  394 1312  750  441  684  249  841  147  528
  594  470  957  542  802 1355 1150 1329  959 1033 1316  364  438  689
  201 1427  857  933 1181 1395  662 1436  194  967 1496 1169 1145  630
  303 1256  440 1450 1452  465  702 1157  602 1480 1268  713  134  526
 1380  140  629 1356  328 1084  931  692 1069  313  894  556 1344  290
  138  926 1261  472 1002  878  905 1180  121 1136  635 1151  644 1045
  829 1242 1469  896  992 1052 1147 1396  663  119  979  319 1413  944
 1323  532  818  854 1034  771 1401 1431  976 1411 1300  252 1327  832
 1017 1199  504  505  916 1247  685  269 1416  833  307 1311  128  488
  529 1210 1463  675 1385 1403  452  666 1158  228  996  728 1315  322
 1479  797 1070  442  496 1372  920  688 1449 1117  636  506  444  950
  889  555  230 1232  566 1302  812 1476  218 1132 1105  906  849  390
  106 1249  192  553  117  185 1091  723 1220  588 1377 1018 1275  798
  672 1162  508 1482  559  210  928 1001  549 1124  738  570 1130 1192
  343  144 1296 1309  483  810  544 1062 1319  641 1332  756  845  593
 1171  350  921 1144  143 1046  575  156 1283  755  304 1178  329 1362
 1371  202  253  164 1107  759 1305  982  821 1381  480 1473  891 1063
  645 1490  317  422 1485 1368 1448  296 1398 1349  986 1099 1116 1499
  983 1009 1303 1274 1277  587  413 1276  988 1474  163  267  619  302
  443  828  561  426  232 1306 1094  509  775  195  258  471  799  956
  535 1495  446 1245  703  823 1246  622 1287  448  254 1365  538  525
  558  782  362 1236 1112  204 1343  604 1216  646  160  238 1397  306
  991  482 1176  913 1076  727  885  243  806  817 1410 1207 1442  693
  929  562  608  580  970 1179  294  314  316  654  168  381  217  501
  650  141  804  975 1090  346  430  268  167  621  527  883  954  310
  719  725  715  657 1146  182  376  571  384  791 1111 1243 1092 1325
  805  213  118  676 1252  286 1258  932 1041  859  720  946 1184  436
  589  760  887 1318  625  180  586 1012  661  930  342 1230 1271 1278
  607  130  300  583 1418 1269  379  395 1265 1222  341  868 1231  102
  881 1383 1075  374 1086  781  177  500 1425 1454  617 1085  995 1122
  618  546  462 1198 1272  154 1137 1188  188 1333  867  263  938  129
  616  498 1404 1053  289 1376  231  152  882  903 1379  335  722  461
  974 1126  840 1134  248  955  939 1391 1206  287 1441  109 1066  277
  466 1055  265  135  247 1035  266  145 1038 1234 1109 1089  788  124
  660 1186 1464  796  415  769 1003 1366  330 1492 1204  309 1330  469
  697 1262 1050  770  406  203 1308  984  439  793 1451 1182  174  490
  718  433  773  603  874  367  199  481  647 1384  902  819  862 1457
  977  942 1402 1421 1361  917  200  150  179  696  116  363  107 1465
  458 1212 1103  966 1010  326 1098  969 1167  694 1320  536  373  599
  251  131  237 1429  648  735  531  429  968  879  640  412  848  360
 1138  325 1322  299 1030  634  524  256 1060  935  495  282  206  943
  523  507  601  855 1291 1405 1369  999 1202  285  404  736 1498 1200
 1439  499  205  683 1462  949  652  332 1475  337  971 1174  667  560
  172  383 1255  359  401  377  592 1445 1221  866  981  447 1326  748
  990  405  115  790  830 1193 1423  467  271  410 1083  516  224  136
 1029  333 1440  674 1342  898  824  492  598  740  888 1288  104 1108
  479 1351  474  437  884 1370  264 1059  563  457 1313  241 1015  336
 1387  170  208  671  711  737 1470  365  763  567  486  772  301  311
  584  880  392  148  708 1259  786  370  678  146  581  918 1238  585
  741  552  369  717  543  964  792  611  176  897  600 1054  428  181
  211 1079  590  305  953  478 1375  244  511 1294  196  734 1239 1253
 1128 1336  234  766  261 1194  431  572 1422 1297  574  355  207  706
  280  726  414  352 1224  459 1254 1131  835 1172 1266  783  219 1213
 1096 1251 1394  605 1064 1337  937  157  754 1168  155 1444  189  911
 1321 1154  557  642  801  161 1382 1037  105  582  704  345 1120 1378
  468  613 1023  628]
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 588
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: int64
 ----------------------------------------------------------------------------------------------------
Columna: Department
 ----------------------------------------------------------------------------------------------------
Valores unicos: <StringArray>
['Sales', 'Research & Development', nan, 'Human Resources']
Length: 4, dtype: str
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 1470
 ----------------------------------------------------------------------------------------------------
Valores nulos: 29
 ----------------------------------------------------------------------------------------------------
El tipo de dato: str
 ----------------------------------------------------------------------------------------------------
Columna: DistanceFromHome
 ----------------------------------------------------------------------------------------------------
Valores unicos: [ 1  8  2  3 24 23 27 16 15 26 19 21  5 11  9  7  6 10  4 25 12 18 29 22
 14 20 28 17 13]
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 1445
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: int64
 ----------------------------------------------------------------------------------------------------
Columna: Education
 ----------------------------------------------------------------------------------------------------
Valores unicos: [2 1 4 3 5]
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 1469
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: int64
 ----------------------------------------------------------------------------------------------------
Columna: EducationField
 ----------------------------------------------------------------------------------------------------
Valores unicos: <StringArray>
[   'Life Sciences',            'Other',          'Medical',
                nan,        'Marketing', 'Technical Degree',
  'Human Resources']
Length: 7, dtype: str
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 1467
 ----------------------------------------------------------------------------------------------------
Valores nulos: 58
 ----------------------------------------------------------------------------------------------------
El tipo de dato: str
 ----------------------------------------------------------------------------------------------------
Columna: EmployeeCount
 ----------------------------------------------------------------------------------------------------
Valores unicos: [1]
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 1473
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: int64
 ----------------------------------------------------------------------------------------------------
Columna: EmployeeNumber
 ----------------------------------------------------------------------------------------------------
Valores unicos: [   1    2    4 ... 2064 2065 2068]
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 4
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: int64
 ----------------------------------------------------------------------------------------------------
Columna: EnvironmentSatisfaction
 ----------------------------------------------------------------------------------------------------
Valores unicos: [2 3 4 1]
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 1470
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: int64
 ----------------------------------------------------------------------------------------------------
Columna: Gender
 ----------------------------------------------------------------------------------------------------
Valores unicos: <StringArray>
['Female', 'Male']
Length: 2, dtype: str
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 1472
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: str
 ----------------------------------------------------------------------------------------------------
Columna: HourlyRate
 ----------------------------------------------------------------------------------------------------
Valores unicos: [ 94  61  92  56  40  79  81  67  44  84  49  31  93  50  51  80  96  78
  45  82  53  83  58  72  48  42  41  86  97  75  33  37  73  98  36  47
  71  30  43  99  59  95  57  76  87  66  55  32  52  70  62  64  63  60
 100  46  39  77  35  91  54  34  90  65  88  85  89  68  69  74  38]
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 1403
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: int64
 ----------------------------------------------------------------------------------------------------
Columna: JobInvolvement
 ----------------------------------------------------------------------------------------------------
Valores unicos: [3 2 4 1]
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 1470
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: int64
 ----------------------------------------------------------------------------------------------------
Columna: JobLevel
 ----------------------------------------------------------------------------------------------------
Valores unicos: [2 1 3 4 5]
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 1469
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: int64
 ----------------------------------------------------------------------------------------------------
Columna: JobRole
 ----------------------------------------------------------------------------------------------------
Valores unicos: <StringArray>
[          ' sales executive ',        ' research scientist ',
     ' laboratory technician ',    ' manufacturing director ',
 ' healthcare representative ',                   ' manager ',
      ' sales representative ',         ' research director ',
           ' human resources ']
Length: 9, dtype: str
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 1465
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: str
 ----------------------------------------------------------------------------------------------------
Columna: JobSatisfaction
 ----------------------------------------------------------------------------------------------------
Valores unicos: [ 4.  2.  3.  1. nan]
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 1469
 ----------------------------------------------------------------------------------------------------
Valores nulos: 29
 ----------------------------------------------------------------------------------------------------
El tipo de dato: float64
 ----------------------------------------------------------------------------------------------------
Columna: MaritalStatus
 ----------------------------------------------------------------------------------------------------
Valores unicos: <StringArray>
['Single', 'Married', 'Divorced', nan, 'Marreid']
Length: 5, dtype: str
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 1469
 ----------------------------------------------------------------------------------------------------
Valores nulos: 132
 ----------------------------------------------------------------------------------------------------
El tipo de dato: str
 ----------------------------------------------------------------------------------------------------
Columna: MonthlyIncome
 ----------------------------------------------------------------------------------------------------
Valores unicos: [5993. 5130. 2090. ... 9991. 5390. 4404.]
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 137
 ----------------------------------------------------------------------------------------------------
Valores nulos: 14
 ----------------------------------------------------------------------------------------------------
El tipo de dato: float64
 ----------------------------------------------------------------------------------------------------
Columna: MonthlyRate
 ----------------------------------------------------------------------------------------------------
Valores unicos: [19479 24907  2396 ...  5174 13243 10228]
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 47
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: int64
 ----------------------------------------------------------------------------------------------------
Columna: NumCompaniesWorked
 ----------------------------------------------------------------------------------------------------
Valores unicos: [8 1 6 9 0 4 5 2 7 3]
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 1464
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: int64
 ----------------------------------------------------------------------------------------------------
Columna: Over18
 ----------------------------------------------------------------------------------------------------
Valores unicos: <StringArray>
['Y']
Length: 1, dtype: str
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 1473
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: str
 ----------------------------------------------------------------------------------------------------
Columna: OverTime
 ----------------------------------------------------------------------------------------------------
Valores unicos: <StringArray>
['Yes', 'No', nan]
Length: 3, dtype: str
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 1471

In [51]:
df_talento.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager', 'ProfitMargen'],
      dtype='str')

In [55]:
display(round(df_talento[['DailyRate', 'HourlyRate', 'MonthlyIncome', 'MonthlyRate']].describe().T), 2)

,count,mean,std,min,25%,50%,75%,max
DailyRate,1474.0,803.0,404.0,102.0,465.0,803.0,1157.0,1499.0
HourlyRate,1474.0,66.0,20.0,30.0,48.0,66.0,84.0,100.0
MonthlyIncome,1460.0,6497.0,4706.0,1009.0,2909.0,4907.0,8377.0,19999.0
MonthlyRate,1474.0,14329.0,7120.0,2094.0,8054.0,14248.0,20466.0,26999.0

2

In [63]:
df_talento[['DailyRate', 'HourlyRate', 'MonthlyIncome', 'MonthlyRate', 'JobRole']].sample(2)

,DailyRate,HourlyRate,MonthlyIncome,MonthlyRate,JobRole
312,192,32,2695.0,7747,research scientist
1471,1084,57,4450.0,26250,manufacturing director

In [66]:
df_talento.groupby("JobLevel")[['DailyRate', 'HourlyRate', 'MonthlyIncome', 'MonthlyRate']].mean()

           DailyRate  HourlyRate  MonthlyIncome   MonthlyRate
JobLevel
1         802.812500   66.740809    2784.527778  13682.580882
2         794.529851   65.787313    5499.277358  14812.188433
3         832.086758   64.164384    9816.212963  14653.420091
4         774.452830   65.679245   15503.783019  14538.547170
5         815.449275   65.724638   19181.029412  14312.057971

In [67]:
df_limpio = df_talento.drop(columns=["DailyRate", "HourlyRate",	"MonthlyRate", "EmployeeCount", "Over18"])

In [69]:
df_limpio.drop(columns=['ProfitMargen'], inplace=True)

In [70]:
df_limpio.shape

(1474, 30)

In [71]:
df_limpio.sample()

,Age,Attrition,BusinessTravel,Department,DistanceFromHome,Education,EducationField,EmployeeNumber,EnvironmentSatisfaction,Gender,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,NumCompaniesWorked,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
796,25.0,Yes,Travel_Rarely,Research & Development,4,1,Technical Degree,1106,4,Male,3,1,laboratory technician,4.0,Married,3691.0,1,Yes,15,3,2,80.0,1,7,3.0,4,7,7,5,6.0

In [72]:
analisis_columnas(df_limpio)

Columna: Age
 ----------------------------------------------------------------------------------------------------
Valores unicos: [41. 49. 37. 33. 27. 32. 59. 30. 38. 36. 35. 29. 31. 34. 28. 22. 53. 24.
 21. 42. 44. 46. 39. 43. 50. 26. 48. nan 55. 45. 56. 23. 51. 40. 54. 58.
 20. 25. 19. 57. 52. 47. 18. 60.]
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 1430
 ----------------------------------------------------------------------------------------------------
Valores nulos: 73
 ----------------------------------------------------------------------------------------------------
El tipo de dato: float64
 ----------------------------------------------------------------------------------------------------
Columna: Attrition
 ----------------------------------------------------------------------------------------------------
Valores unicos: <StringArray>
['Yes', 'No']
Length: 2, dtype: str
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 1472
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: str
 ----------------------------------------------------------------------------------------------------
Columna: BusinessTravel
 ----------------------------------------------------------------------------------------------------
Valores unicos: <StringArray>
['Travel_Rarely', 'Travel_Frequently', 'Non-Travel', nan]
Length: 4, dtype: str
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 1470
 ----------------------------------------------------------------------------------------------------
Valores nulos: 117
 ----------------------------------------------------------------------------------------------------
El tipo de dato: str
 ----------------------------------------------------------------------------------------------------
Columna: Department
 ----------------------------------------------------------------------------------------------------
Valores unicos: <StringArray>
['Sales', 'Research & Development', nan, 'Human Resources']
Length: 4, dtype: str
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 1470
 ----------------------------------------------------------------------------------------------------
Valores nulos: 29
 ----------------------------------------------------------------------------------------------------
El tipo de dato: str
 ----------------------------------------------------------------------------------------------------
Columna: DistanceFromHome
 ----------------------------------------------------------------------------------------------------
Valores unicos: [ 1  8  2  3 24 23 27 16 15 26 19 21  5 11  9  7  6 10  4 25 12 18 29 22
 14 20 28 17 13]
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 1445
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: int64
 ----------------------------------------------------------------------------------------------------
Columna: Education
 ----------------------------------------------------------------------------------------------------
Valores unicos: [2 1 4 3 5]
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 1469
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: int64
 ----------------------------------------------------------------------------------------------------
Columna: EducationField
 ----------------------------------------------------------------------------------------------------
Valores unicos: <StringArray>
[   'Life Sciences',            'Other',          'Medical',
                nan,        'Marketing', 'Technical Degree',
  'Human Resources']
Length: 7, dtype: str
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 1467
 ----------------------------------------------------------------------------------------------------
Valores nulos: 58
 ----------------------------------------------------------------------------------------------------
El tipo de dato: str
 ----------------------------------------------------------------------------------------------------
Columna: EmployeeNumber
 ----------------------------------------------------------------------------------------------------
Valores unicos: [   1    2    4 ... 2064 2065 2068]
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 4
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: int64
 ----------------------------------------------------------------------------------------------------
Columna: EnvironmentSatisfaction
 ----------------------------------------------------------------------------------------------------
Valores unicos: [2 3 4 1]
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 1470
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: int64
 ----------------------------------------------------------------------------------------------------
Columna: Gender
 ----------------------------------------------------------------------------------------------------
Valores unicos: <StringArray>
['Female', 'Male']
Length: 2, dtype: str
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 1472
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: str
 ----------------------------------------------------------------------------------------------------
Columna: JobInvolvement
 ----------------------------------------------------------------------------------------------------
Valores unicos: [3 2 4 1]
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 1470
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: int64
 ----------------------------------------------------------------------------------------------------
Columna: JobLevel
 ----------------------------------------------------------------------------------------------------
Valores unicos: [2 1 3 4 5]
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 1469
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: int64
 ----------------------------------------------------------------------------------------------------
Columna: JobRole
 ----------------------------------------------------------------------------------------------------
Valores unicos: <StringArray>
[          ' sales executive ',        ' research scientist ',
     ' laboratory technician ',    ' manufacturing director ',
 ' healthcare representative ',                   ' manager ',
      ' sales representative ',         ' research director ',
           ' human resources ']
Length: 9, dtype: str
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 1465
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: str
 ----------------------------------------------------------------------------------------------------
Columna: JobSatisfaction
 ----------------------------------------------------------------------------------------------------
Valores unicos: [ 4.  2.  3.  1. nan]
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 1469
 ----------------------------------------------------------------------------------------------------
Valores nulos: 29
 ----------------------------------------------------------------------------------------------------
El tipo de dato: float64
 ----------------------------------------------------------------------------------------------------
Columna: MaritalStatus
 ----------------------------------------------------------------------------------------------------
Valores unicos: <StringArray>
['Single', 'Married', 'Divorced', nan, 'Marreid']
Length: 5, dtype: str
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 1469
 ----------------------------------------------------------------------------------------------------
Valores nulos: 132
 ----------------------------------------------------------------------------------------------------
El tipo de dato: str
 ----------------------------------------------------------------------------------------------------
Columna: MonthlyIncome
 ----------------------------------------------------------------------------------------------------
Valores unicos: [5993. 5130. 2090. ... 9991. 5390. 4404.]
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 137
 ----------------------------------------------------------------------------------------------------
Valores nulos: 14
 ----------------------------------------------------------------------------------------------------
El tipo de dato: float64
 ----------------------------------------------------------------------------------------------------
Columna: NumCompaniesWorked
 ----------------------------------------------------------------------------------------------------
Valores unicos: [8 1 6 9 0 4 5 2 7 3]
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 1464
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: int64
 ----------------------------------------------------------------------------------------------------
Columna: OverTime
 ----------------------------------------------------------------------------------------------------
Valores unicos: <StringArray>
['Yes', 'No', nan]
Length: 3, dtype: str
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 1471
 ----------------------------------------------------------------------------------------------------
Valores nulos: 44
 ----------------------------------------------------------------------------------------------------
El tipo de dato: str
 ----------------------------------------------------------------------------------------------------
Columna: PercentSalaryHike
 ----------------------------------------------------------------------------------------------------
Valores unicos: [11 23 15 12 13 20 22 21 17 14 16 18 19 24 25]
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 1459
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: int64
 ----------------------------------------------------------------------------------------------------
Columna: PerformanceRating
 ----------------------------------------------------------------------------------------------------
Valores unicos: [3 4]
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 1472
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: int64
 ----------------------------------------------------------------------------------------------------
Columna: RelationshipSatisfaction
 ----------------------------------------------------------------------------------------------------
Valores unicos: [1 4 2 3]
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 1470
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: int64
 ----------------------------------------------------------------------------------------------------
Columna: StandardHours
 ----------------------------------------------------------------------------------------------------
Valores unicos: [80. nan]
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 1472
 ----------------------------------------------------------------------------------------------------
Valores nulos: 164
 ----------------------------------------------------------------------------------------------------
El tipo de dato: float64
 ----------------------------------------------------------------------------------------------------
Columna: StockOptionLevel
 ----------------------------------------------------------------------------------------------------
Valores unicos: [0 1 3 2]
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 1470
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: int64
 ----------------------------------------------------------------------------------------------------
Columna: TotalWorkingYears
 ----------------------------------------------------------------------------------------------------
Valores unicos: [ 8 10  7  6 12  1 17  5  3 31 13  0 26 24 22  9 19  2 23 14 15  4 29 28
 21 25 20 11 16 37 38 30 40 18 36 34 32 33 35 27]
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 1434
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: int64
 ----------------------------------------------------------------------------------------------------
Columna: TrainingTimesLastYear
 ----------------------------------------------------------------------------------------------------
Valores unicos: [ 0.  3.  2.  5.  1.  4. nan  6.]
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 1466
 ----------------------------------------------------------------------------------------------------
Valores nulos: 88
 ----------------------------------------------------------------------------------------------------
El tipo de dato: float64
 ----------------------------------------------------------------------------------------------------
Columna: WorkLifeBalance
 ----------------------------------------------------------------------------------------------------
Valores unicos: [1 3 2 4]
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 1470
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: int64
 ----------------------------------------------------------------------------------------------------
Columna: YearsAtCompany
 ----------------------------------------------------------------------------------------------------
Valores unicos: [ 6 10  0  8  2  7  1  9  5  4 25  3 12 14 22 15 27 21 17 11 13 37 16 20
 40 24 33 19 36 18 29 31 32 34 26 30 23]
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 1437
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: int64
 ----------------------------------------------------------------------------------------------------
Columna: YearsInCurrentRole
 ----------------------------------------------------------------------------------------------------
Valores unicos: [ 4  7  0  2  5  9  8  3  6 13  1 15 14 16 11 10 12 18 17]
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 1455
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: int64
 ----------------------------------------------------------------------------------------------------
Columna: YearsSinceLastPromotion
 ----------------------------------------------------------------------------------------------------
Valores unicos: [ 0  1  3  2  7  4  8  6  5 15  9 13 12 10 11 14]
 ----------------------------------------------------------------------------------------------------
Valores duplicados: 1458
 ----------------------------------------------------------------------------------------------------
Valores nulos: 0
 ----------------------------------------------------------------------------------------------------
El tipo de dato: int64
 ----------------------------------------------------------------------------------------------------
Columna: YearsWithCurrManager
 ----------------------------------------------------------------------------------------------------
Valores unicos: [ 5.  7.  0.  2.  6. nan  8.  3. 11. 17.  4.  1. 12.  9. 10. 15. 13. 16.
 14.]

In [83]:
df_limpio.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1469    False
1470     True
1471     True
1472     True
1473     True
Length: 1474, dtype: bool

In [ ]:
#df_limpio.drop_duplicates(inplace=True)

In [75]:
duplicados = df_limpio[df_limpio.duplicated()]
print(duplicados.index)

RangeIndex(start=1470, stop=1474, step=1)

In [82]:
df_limpio.iloc[1470:1475:1]

,Age,Attrition,BusinessTravel,Department,DistanceFromHome,Education,EducationField,EmployeeNumber,EnvironmentSatisfaction,Gender,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,NumCompaniesWorked,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
1470,28.0,No,Travel_Rarely,Sales,5,3,Medical,1469,4,Male,3,2,sales executive,1.0,Single,8463.0,0,No,18,3,4,NaN,0,6,4.0,3,5,4,1,NaN
1471,53.0,No,Travel_Rarely,Research & Development,13,2,Medical,250,4,Female,4,2,manufacturing director,1.0,Divorced,4450.0,1,No,11,3,3,NaN,2,5,3.0,3,4,2,1,3.0
1472,24.0,Yes,Travel_Rarely,Human Resources,22,1,Human Resources,1714,4,Male,1,1,human resources,3.0,Married,1555.0,1,No,11,3,3,80.0,1,1,2.0,3,1,0,0,0.0
1473,45.0,No,Travel_Rarely,Research & Development,7,3,Life Sciences,86,2,Male,3,3,research scientist,1.0,Divorced,9724.0,2,No,17,3,3,NaN,1,25,2.0,3,1,0,0,0.0

In [78]:
duplicadas = df_limpio.loc[df_limpio.duplicated()]
print(duplicadas)

       Age Attrition BusinessTravel              Department  DistanceFromHome  \
1470  28.0        No  Travel_Rarely                   Sales                 5
1471  53.0        No  Travel_Rarely  Research & Development                13
1472  24.0       Yes  Travel_Rarely         Human Resources                22
1473  45.0        No  Travel_Rarely  Research & Development                 7

      Education   EducationField  EmployeeNumber  EnvironmentSatisfaction  \
1470          3          Medical            1469                        4
1471          2          Medical             250                        4
1472          1  Human Resources            1714                        4
1473          3    Life Sciences              86                        2

      Gender  JobInvolvement  JobLevel                   JobRole  \
1470    Male               3         2          sales executive
1471  Female               4         2   manufacturing director
1472    Male               1         1          human resources
1473    Male               3         3       research scientist

      JobSatisfaction MaritalStatus  MonthlyIncome  NumCompaniesWorked  \
1470              1.0        Single         8463.0                   0
1471              1.0      Divorced         4450.0                   1
1472              3.0       Married         1555.0                   1
1473              1.0      Divorced         9724.0                   2

     OverTime  PercentSalaryHike  PerformanceRating  RelationshipSatisfaction  \
1470       No                 18                  3                         4
1471       No                 11                  3                         3
1472       No                 11                  3                         3
1473       No                 17                  3                         3

      StandardHours  StockOptionLevel  TotalWorkingYears  \
1470            NaN                 0                  6
1471            NaN                 2                  5
1472           80.0                 1                  1
1473            NaN                 1                 25

      TrainingTimesLastYear  WorkLifeBalance  YearsAtCompany  \
1470                    4.0                3               5
1471                    3.0                3               4
1472                    2.0                3               1
1473                    2.0                3               1

      YearsInCurrentRole  YearsSinceLastPromotion  YearsWithCurrManager
1470                   4                        1                   NaN
1471                   2                        1                   3.0
1472                   0                        0                   0.0
1473                   0                        0                   0.0

In [84]:
df_limpio.tail()

,Age,Attrition,BusinessTravel,Department,DistanceFromHome,Education,EducationField,EmployeeNumber,EnvironmentSatisfaction,Gender,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,NumCompaniesWorked,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
1469,34.0,No,Travel_Rarely,Research & Development,8,3,Medical,2068,2,Male,4,2,laboratory technician,3.0,Married,4404.0,2,No,12,3,1,NaN,0,6,3.0,4,4,3,1,2.0
1470,28.0,No,Travel_Rarely,Sales,5,3,Medical,1469,4,Male,3,2,sales executive,1.0,Single,8463.0,0,No,18,3,4,NaN,0,6,4.0,3,5,4,1,NaN
1471,53.0,No,Travel_Rarely,Research & Development,13,2,Medical,250,4,Female,4,2,manufacturing director,1.0,Divorced,4450.0,1,No,11,3,3,NaN,2,5,3.0,3,4,2,1,3.0
1472,24.0,Yes,Travel_Rarely,Human Resources,22,1,Human Resources,1714,4,Male,1,1,human resources,3.0,Married,1555.0,1,No,11,3,3,80.0,1,1,2.0,3,1,0,0,0.0
1473,45.0,No,Travel_Rarely,Research & Development,7,3,Life Sciences,86,2,Male,3,3,research scientist,1.0,Divorced,9724.0,2,No,17,3,3,NaN,1,25,2.0,3,1,0,0,0.0